### PR TITLE
Updated plugin to use newer molecule APIs

### PR DESCRIPTION
**Pull request by bonddim**
#4

### CODE REVIEW

**Comment by snesbittsea** [comment]
@bonddim 

Thanks for submitting this!

 Would it be possible to use the ansible package module in the prepare.yml to install base software? 

The raw module isn't idempotent which will slow down the test cycle.

Not sure what I'm doing as maintainer yet, so bear with me!

-steve

**Comment by bonddim** [comment]
@snesbittsea
We cant use **package** module because there is no python interpreter in bare LXC containers

**Comment by snesbittsea** [comment]
@Bonddim



Doh! 



This might be doable using a filter which is something I will look into. (The docker driver has a filter)



But for now I'll work on getting this merged in.



Thx!



-steve




---- On Fri, 12 Feb 2021 13:00:30 -0800 Dmytro Bondar <notifications@github.com> wrote ----




https://github.com/snesbittsea
 We cant use package module because there is no python interpreter in bare LXC containers

**Comment by snesbittsea** [comment]
@decentral1se

Would you grant me authorization to merge in this pull request per issue 3306 (transferring maintainer)

Thx,

-steve

**Review by ssbarnea — APPROVED** [review]
LGTM but I did not test it.

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
